SELECT CAR_ID, CAR_TYPE, FEE
FROM (
    SELECT C.CAR_ID, C.CAR_TYPE, 
        TRUNCATE(30 * C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100, 0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
        ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
        AND C.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-11-30'
                AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01'
        )
) AS SUB
WHERE SUB.FEE >= 500000 AND SUB.FEE < 2000000
ORDER BY SUB.FEE DESC, SUB.CAR_TYPE, SUB.CAR_ID DESC