-- 코드를 작성해주세요
SELECT 
    CASE
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') < '04-01' THEN '1Q'
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') < '07-01' THEN '2Q'
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') < '10-01' THEN '3Q'
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') >= '10-01' THEN '4Q'
    END
AS QUARTER,
COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER