-- 코드를 입력하세요
SELECT H.HISTORY_ID, 
ROUND((DATEDIFF(H.END_DATE, START_DATE) + 1) * C.DAILY_FEE * ((100 - IFNULL(D.DISCOUNT_RATE, 0)) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H 
JOIN CAR_RENTAL_COMPANY_CAR AS C ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D ON D.CAR_TYPE = C.CAR_TYPE AND D.DURATION_TYPE = (
CASE
    WHEN DATEDIFF(H.END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
    WHEN DATEDIFF(H.END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
    WHEN DATEDIFF(H.END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    ELSE '할인 없음'
END
)
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC