-- 코드를 작성해주세요
WITH SUB AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, S.SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN SUB S ON YEAR(E.DIFFERENTIATION_DATE) = S.YEAR
ORDER BY YEAR, YEAR_DEV
