-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT I.ID, N.FISH_NAME, I.LENGTH,
        RANK() OVER(PARTITION BY I.FISH_TYPE ORDER BY I.LENGTH DESC) AS SIZE_RANK
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
) AS SUB
WHERE SIZE_RANK = 1
ORDER BY ID