-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
-- BOOK_SALES - 2022년 1월만 남기기
-- BOOK_ID로 JOIN
FROM BOOK AS B JOIN (
    SELECT *
    FROM BOOK_SALES
    WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01') AS S
ON B.BOOK_ID = S.BOOK_ID
-- CATEGORY로 GROUP
GROUP BY CATEGORY
ORDER BY CATEGORY
