-- 코드를 입력하세요
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME,
        RANK() OVER(PARTITION BY CATEGORY
                   ORDER BY PRICE DESC) AS CATEGORY_RANK
    FROM FOOD_PRODUCT
) AS SUB
WHERE CATEGORY_RANK = 1
    AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC